### ISSUE TITLE
Add error modifying lenses

### ISSUE THREAD

**Issue by rohit507** [ChrisPenner/lens-errors#1]
I tend to like having the ability to capture contextual in formation in an error like so: 

```
data Err c e = Ctxt c (Err c e) | Err e 

withCtxt :: c -> Either (Err c e) a -> Either (Err c e) a 
withCtxt = lmap . Ctxt
```

Is it possible to add a lens combinator that can modify the error (if it occurs) while otherwise being the `id` lens? 

Thanks, 
Rohit

**Comment by ChrisPenner** [comment]
Added `adjustingErrors` and `adjustingErrorsWith` 👍
